version: '3'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - "5436:5436"
    expose:
      - "5436"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_challenge
  message-api:
    container_name: message-app
    image: openjdk:11-jre-slim
    restart: always
    depends_on:
      - postgres-db
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
    expose:
      - "8080"
    working_dir: /var/www/html
    command: bash -c "java -jar target/chatchallenge-1.0.0.jar"
  webapp:
    container_name: webapp
    build: ../message-ui
    ports:
      - "3000:3000"
    expose:
      - "3000"
    labels:
      NAME: "webapp"
    depends_on:
      - message-api